[project]
name = "learning-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gevent>=25.9.1",
    "invoke>=2.2.0",
    "pytest>=8.4.2",
]
